# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: .submitit/%j
timeout_min: 120
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
exclude: null
signal_delay_s: 600
max_num_timeout: 20
additional_parameters:
  gpus: 1
  output: "slurm_logs/%j_%t.out"
  error: "slurm_logs/%j_%t.err"
array_parallelism: 16
setup: []
constraint: "hi"
mem_gb: 32
