# Wagner Deep Cross-Entropy algorithm configuration
_target_: thesis.algorithms.deep_cross_entropy.WagnerDeepCrossEntropy

# Training hyperparameters
iterations: 15000
batch_size: 4096
learning_rate: 0.0001
elite_proportion: 0.1

# Device will be passed from main config
device: null
