# Simple Hydra Configuration
# Everything in one file - no complex defaults or multiple config files!

# Experiment settings
seed: 42
device: auto  # auto, cpu, cuda, mps
experiment_name: simple_experiment

# Model configuration  
model:
  _target_: models.wagner_model.WagnerModel
  n: 19

# Problem configuration
problem:
  _target_: problems.wagner_corollary_2_1.WagnerCorollary2_1
  n: 19

# Algorithm configuration
algorithm:
  _target_: algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 1000  # Reduced for quick testing
  batch_size: 512   # Reduced for quick testing
  learning_rate: 0.001
  elite_proportion: 0.1

# Logger configuration - Simple console logger
logger:
  _target_: experiment_logger.console_logger.ConsoleLogger
  experiment_name: ${experiment_name}

# Hydra output directory (optional - Hydra will use default if not specified)
hydra:
  run:
    dir: hydra_outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}