# Simple Hydra Configuration
# Everything in one file - no complex defaults or multiple config files!

# Experiment settings
seed: 42
device: auto  # auto, cpu, cuda, mps
experiment_name: test
n: 19

# Model configuration  
model:
  _target_: models.wagner_model.WagnerModel
  n: ${n}

# Problem configuration
problem:
  _target_: problems.wagner_corollary_2_1.WagnerCorollary2_1
  n: ${n}

# Algorithm configuration
algorithm:
  _target_: algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 1000  # Reduced for quick testing
  batch_size: 512   # Reduced for quick testing
  learning_rate: 0.001
  elite_proportion: 0.1

# Logger configuration - wandb and progress bar enabled by default
logger:
  _target_: experiment_logger.ExperimentLogger
  experiment_name: ${experiment_name}
  use_progress_bar: true
  
  # WandB-specific settings
  project: thesis-experiments
  entity: null  # Set to your WandB username/team, or leave null for default
  wandb_mode: online  # online, offline, disabled
  
  # Authentication (will use WANDB_API_KEY environment variable)
  api_key: null  # Leave null to use environment variable (recommended for HPC)
  
  # WandB run configuration (passed to wandb.init)
  tags: []
  notes: ""
  save_code: true

# Hydra output directory (optional - Hydra will use default if not specified)
hydra:
  run:
    dir: hydra_outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}