defaults:
  - base_config
  - override hydra/launcher: HPC_2HRS_GPU
  - _self_

experiment_name: slurm-test
n: 10

logger:
  wandb_mode: disabled
  use_progress_bar: true


problem:
  _target_: thesis.problems.wagner_corollary_2_1.WagnerCorollary21
  n: ${n}

model:
  _target_: thesis.models.wagner_model.WagnerModel
  n: ${n}

algorithm:
  _target_: thesis.algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 500
  batch_size: 16
  learning_rate: 0.001
  elite_proportion: 0.1
