experiment_name: "srg_${srg_params.0}_${srg_params.1}_${srg_params.2}_${srg_params.3}"
defaults:
  - base_config
  - override /hydra/launcher: HPC_2HRS_GPU
  - _self_

# Multirun configuration for all SRG parameter sets up to 16 vertices
# Based on https://aeb.win.tue.nl/graphs/srg/srgtab1-50.html
hydra:
  mode: MULTIRUN
  job:
    name: "srg_${srg_params.0}_${srg_params.1}_${srg_params.2}_${srg_params.3}"
  sweeper:
    params:
      # Each line represents one valid SRG parameter set (n,k,lambda,mu) as tuple
      +srg_params: "[5,2,0,1],[9,4,1,2],[10,3,0,1],[10,6,4,4],[13,6,2,3],[15,6,1,3],[15,8,4,4],[16,5,0,2],[16,6,2,2],[16,9,12,16]"

# Default values (will be overridden by sweep)
srg_params: [5, 2, 0, 1]

logger:
  wandb_mode: "online"
  use_progress_bar: false
  group: "strongly_regular_graphs"
  tags: ["multirun", "basic-ff", "srg-search", "up-to-16-vertices", "slurm", "n=${srg_params.0}", "k=${srg_params.1}", "lambda=${srg_params.2}", "mu=${srg_params.3}"]           
  notes: "Search for (${srg_params.0},${srg_params.1},${srg_params.2},${srg_params.3})-SRG from Andries Brouwer's table"

problem:
  _target_: thesis.problems.StronglyRegularGraphs
  srg_params: ${srg_params}

model:
  _target_: thesis.models.FFModel
  n: ${srg_params.0}
  hidden_layer_sizes: [512, 128, 128, 128, 64, 16]

algorithm:
  _target_: thesis.algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 10
  batch_size: 8192
  learning_rate: 0.001
  elite_proportion: 0.1
  early_stopping_patience: 300
