defaults:
  - base_config
  - _self_

experiment_name: null  # Use random wandb name
n: 17
k: 8
lambda_param: 3
mu: 4

# Experiment organization - what is this testing?
logger:
  group: "strongly_regular_graphs"
  tags: ["n=${n}", "paley-graph"]           
  notes: "Searching for a (${n}, ${k}, ${lambda_param}, ${mu})-SRG"

problem:
  _target_: thesis.problems.StronglyRegularGraphs
  n: ${n}
  k: ${k}
  lambda_param: ${lambda_param}
  mu: ${mu}

model:
  _target_: thesis.models.wagner_model.WagnerModel
  n: ${n}

algorithm:
  _target_: thesis.algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 1000
  batch_size: 8192
  learning_rate: 0.001
  elite_proportion: 0.1

