defaults:
  - base_config
  - _self_

# SRG parameters: [n, k, lambda, mu]
# Override this when running experiments
srg_params: [10, 3, 0, 1]  # Default to Peterson graph parameters

# Extract individual parameters for convenience
n: ${srg_params.0}
k: ${srg_params.1}
lambda_param: ${srg_params.2}
mu: ${srg_params.3}

# Dynamic experiment name based on SRG parameters
experiment_name: "srg_${n}_${k}_${lambda_param}_${mu}_ff"

logger:
  group: "strongly_regular_graphs"
  tags: ["n=${n}", "k=${k}", "lambda=${lambda_param}", "mu=${mu}"]
  notes: "Searching for a (${n}, ${k}, ${lambda_param}, ${mu})-SRG"

problem:
  _target_: combo_dl.problems.StronglyRegularGraphs
  srg_params: ${srg_params}

model:
  _target_: combo_dl.models.wagner_model.WagnerModel
  n: ${n}

algorithm:
  _target_: combo_dl.algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 1000
  batch_size: 8192
  learning_rate: 0.001
  elite_proportion: 0.1
