defaults:
  - base_config
  - _self_

experiment_name: null  # Use random wandb name
n: 19

# Experiment organization - what is this testing?
logger:
  group: "wagner_corollary_2_1"  # Groups all Wagner Corollary 2.1 experiments
  tags: ["n=${n}"]               # Categorize this specific run
  notes: "Testing Wagner Corollary 2.1 with n=${n} and original model from the paper"

problem:
  _target_: thesis.problems.wagner_corollary_2_1.WagnerCorollary21
  n: ${n}

model:
  _target_: thesis.models.wagner_model.WagnerModel
  n: ${n}

algorithm:
  _target_: thesis.algorithms.deep_cross_entropy.WagnerDeepCrossEntropy
  iterations: 500
  batch_size: 32
  learning_rate: 0.001
  elite_proportion: 0.1

