#!/usr/bin/env python3
"""Find the optimal batch size for Cayley DSRG search.

Tests a range of batch sizes on a real parameter set, measuring:
  - Enumeration throughput (subsets generated per second)
  - DSRG check throughput (subsets checked per second)
  - Combined throughput (end-to-end subsets per second)
  - Peak memory usage

The bottleneck is check_dsrg, which allocates (B, n, n) float tensors.
Larger batches amortize overhead but eventually hit memory limits or
diminishing returns.

Usage:
    python scripts/tune_batch_size.py [n k t lambda mu]
    python scripts/tune_batch_size.py              # default: 50 21 12 8 9
    python scripts/tune_batch_size.py 36 10 5 2 3
"""

from __future__ import annotations

import gc
import sys
import time

import torch

from cayley_search.generate import (
    _classify_elements,
    _count_t_valid_subsets,
    _t_valid_batches,
    check_dsrg,
    load_group_tables,
)


def _get_mem_mb(device: torch.device) -> float:
    """Current allocated memory in MB (GPU only; returns 0 for CPU)."""
    if device.type == "cuda":
        return torch.cuda.memory_allocated(device) / 1e6
    if device.type == "mps":
        return torch.mps.current_allocated_memory() / 1e6
    return 0.0


def _peak_mem_mb(device: torch.device) -> float:
    """Peak allocated memory in MB since last reset."""
    if device.type == "cuda":
        return torch.cuda.max_memory_allocated(device) / 1e6
    if device.type == "mps":
        return torch.mps.driver_allocated_memory() / 1e6
    return 0.0


def _reset_peak(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)


def bench_batch_size(
    n: int, k: int, t: int, lambda_: int, mu: int,
    batch_size: int,
    group,
    involutions: list[int],
    pairs: list[tuple[int, int]],
    device: torch.device,
    num_batches: int = 40,
) -> dict | None:
    """Time `num_batches` batches at the given batch_size. Returns stats or None on OOM."""
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()
    elif device.type == "mps":
        torch.mps.empty_cache()

    _reset_peak(device)
    mem_before = _get_mem_mb(device)

    gen_time = 0.0
    check_time = 0.0
    total_subsets = 0
    found = 0

    try:
        batch_iter = _t_valid_batches(involutions, pairs, k, t, batch_size, device)
        for i, batch in enumerate(batch_iter):
            if i >= num_batches:
                break

            t0 = time.perf_counter()
            # batch is already generated by the iterator
            gen_done = time.perf_counter()

            dsrg = check_dsrg(batch, group, t, lambda_, mu)
            check_done = time.perf_counter()

            total_subsets += batch.shape[0]
            found += dsrg.shape[0]

            # First batch includes iterator startup; attribute to gen
            gen_time += gen_done - t0
            check_time += check_done - gen_done

        # Force sync for accurate timing
        if device.type == "cuda":
            torch.cuda.synchronize(device)
        elif device.type == "mps":
            torch.mps.synchronize()

    except RuntimeError as e:
        if "out of memory" in str(e).lower() or "not enough" in str(e).lower():
            return None
        raise

    peak_mem = _peak_mem_mb(device)
    wall = gen_time + check_time

    return {
        "batch_size": batch_size,
        "batches": min(i + 1, num_batches),
        "total_subsets": total_subsets,
        "wall_s": round(wall, 3),
        "gen_s": round(gen_time, 3),
        "check_s": round(check_time, 3),
        "subsets_per_s": int(total_subsets / wall) if wall > 0 else 0,
        "check_per_s": int(total_subsets / check_time) if check_time > 0 else 0,
        "peak_mem_mb": round(peak_mem, 1),
        "mem_delta_mb": round(peak_mem - mem_before, 1),
        "found": found,
    }


def main():
    # Parse parameters
    if len(sys.argv) == 6:
        n, k, t, lam, mu = (int(x) for x in sys.argv[1:6])
    elif len(sys.argv) == 1:
        n, k, t, lam, mu = 50, 21, 12, 8, 9
    else:
        print("Usage: python scripts/tune_batch_size.py [n k t lambda mu]")
        sys.exit(1)

    # Device selection
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")

    print(f"DSRG({n}, {k}, {t}, {lam}, {mu})")
    print(f"Device: {device}")

    # Load first group
    groups = load_group_tables(n, device=device)
    if not groups:
        print("No nonabelian groups found")
        sys.exit(1)

    group = groups[0]
    involutions, pairs = _classify_elements(group)
    tv = _count_t_valid_subsets(len(involutions), len(pairs), k, t)
    print(f"Group: {group.name} (order {n})")
    print(f"Involutions: {len(involutions)}, Pairs: {len(pairs)}")
    print(f"T-valid subsets: {tv:,}")

    # Memory estimate: check_dsrg peak is roughly B * n * n * 4 bytes (float32 adjacency)
    # plus B * n * 4 (a_sq_e) plus B * n (bool mask)
    bytes_per_subset = n * n * 4 + n * 4 + n  # approximate
    print(f"Estimated memory per subset in check: ~{bytes_per_subset} bytes")
    print()

    # Batch sizes to test
    batch_sizes = [
        1_000, 2_000, 5_000,
        10_000, 20_000, 50_000,
        100_000, 200_000, 500_000,
        1_000_000, 2_000_000, 5_000_000,
    ]

    # Filter out sizes that would obviously OOM (rough heuristic)
    # Allow up to ~8GB for CUDA, ~8GB for MPS
    max_bytes = 8e9
    batch_sizes = [bs for bs in batch_sizes if bs * bytes_per_subset < max_bytes]

    print(f"{'batch_size':>12}  {'subsets/s':>10}  {'check/s':>10}  "
          f"{'wall(s)':>8}  {'gen(s)':>7}  {'chk(s)':>7}  "
          f"{'peak_MB':>8}  {'delta_MB':>9}  {'found':>5}")
    print("-" * 100)

    best = None
    num_batches = 40

    for bs in batch_sizes:
        result = bench_batch_size(
            n, k, t, lam, mu,
            batch_size=bs,
            group=group,
            involutions=involutions,
            pairs=pairs,
            device=device,
            num_batches=num_batches,
        )

        if result is None:
            print(f"{bs:>12,}  {'OOM':>10}")
            break

        marker = ""
        if best is None or result["subsets_per_s"] > best["subsets_per_s"]:
            best = result
            marker = "  ★"

        print(
            f"{result['batch_size']:>12,}  "
            f"{result['subsets_per_s']:>10,}  "
            f"{result['check_per_s']:>10,}  "
            f"{result['wall_s']:>8.3f}  "
            f"{result['gen_s']:>7.3f}  "
            f"{result['check_s']:>7.3f}  "
            f"{result['peak_mem_mb']:>8.1f}  "
            f"{result['mem_delta_mb']:>9.1f}  "
            f"{result['found']:>5}"
            f"{marker}"
        )

    if best:
        print(f"\nBest throughput: {best['subsets_per_s']:,} subsets/s at batch_size={best['batch_size']:,}")

        # Project full search time
        total_batches = (tv + best["batch_size"] - 1) // best["batch_size"]
        est_seconds = tv / best["subsets_per_s"]
        if est_seconds < 120:
            est_str = f"{est_seconds:.0f}s"
        elif est_seconds < 7200:
            est_str = f"{est_seconds/60:.1f}m"
        elif est_seconds < 86400 * 2:
            est_str = f"{est_seconds/3600:.1f}h"
        else:
            est_str = f"{est_seconds/86400:.1f}d"

        print(f"Estimated time for this group ({tv:,} subsets): {est_str}")
        print(f"Recommended: --batch-size {best['batch_size']}")


if __name__ == "__main__":
    with torch.no_grad():
        main()
