# Wagner model configuration
_target_: models.wagner_model.WagnerModel

# Model parameters
n: 19  # Number of vertices in the graph

# Network architecture (defined in model class)
# - Uses 2 * edges input size (partial solution + position encoding)
# - Hidden layers: [128, 64, 4] 
# - Output: 2 (binary choice per edge)
# - Activation: GELU
# - Dropout: 0.1
